[theme]
primaryColor="#DBADF0"
backgroundColor="#DBADF0"
secondaryBackgroundColor="#ACACFA"
textColor="#4B3B7D"
font = "Thin 100"
codeFont = "JetBrains Mono:https://fonts.googleapis.com/css2?family=JetBrains+Mono&display=swap"
